FROM alpine:3.8

WORKDIR /root/

RUN apk add --force-refresh curl ca-certificates && \
    curl -SLO  https://github.com/alexellis/inlets/releases/download/0.4.0/inlets && \
    chmod +x inlets && \
    apk del curl

CMD ["./inlets"]
